### ISSUE TITLE
Comparison to kopykat-kt/kopykat

### ISSUE THREAD

**Issue by sschuberth** [JavierSegoviaCordoba/kopy#12]
As a guidance for people who are planning to take such a utility library into use, would it make sense to compare to https://github.com/kopykat-kt/kopykat and highlight the differences?

**Comment by JavierSegoviaCordoba** [comment]
It is a good idea, I will add a comparison to the README in coming days.

In summary, this plugin does not generate builders with 1:1 properties like KopyKat does, it generates 9 functions/properties that will be reduced to 2 when context parameters are available (or even 1, as I will add an option to disable, optionally, the `invoke` or the `copy`.

This plugin is a shortcut to what you would write manually, under the hood it modifies the IR so:

```
data class A(val b: B)
data class B(val value: String)

fun main() {
    a.copy {
        b.value = "new value"
    }
}

// Under the hood
fun main() {
    a.copy(b = a.b.copy(value = "new value")
}
```

That has one advantage and one disadvantage.

The advantage is the codegen does not scale linearly, it is limited to a few methods, KopyKat can generate tons of code if you have a lot of properties on your data classes.

The disadvantage is that you need to apply the plugin to get it working. This means you shouldn't use this plugin on libraries that are going to be consumed by people who are not going to apply this plugin, like on open-source libraries or SDKs, if you don't want to force them to apply this plugin.

**Comment by JavierSegoviaCordoba** [comment]
@sschuberth I have created a PR to show the comparison, can you take a look into it?

Pull request: https://github.com/JavierSegoviaCordoba/kopy/pull/20

**Comment by JavierSegoviaCordoba** [comment]
Comparison added to the [README](https://github.com/JavierSegoviaCordoba/kopy/blob/main/README.md#kopykat-comparison)
