### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by inktomi** [JavierSegoviaCordoba/kopy#60]
I see that you license Kopy under Apache 2, and that's listed in the POM file you publish. Some tooling that scans open source repositories for companies also looks for a LICENSE.md file at the root of the repo (Github also triggers off this). 

Could you add the Apache 2 license in a LICENSE.md file?

**Comment by JavierSegoviaCordoba** [comment]
Done!

Commit: https://github.com/JavierSegoviaCordoba/kopy/commit/3624fdd67ee21c22b0f50870d890af7b4be25979
